<!DOCTYPE html><html lang="en"><head><meta name="google-site-verification" content="vBfBdoTFao8u16hPaIUz_Q6etbp9Hm32MoJo_tMwvuE"><script async src="https://www.googletagmanager.com/gtag/js?id=UA-81665290-2"></script><script>window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'UA-81665290-2', { 'anonymize_ip': true, 'cookie_domain': ".stellarium-web.org", "cookie_flags": "SameSite=None;Secure" }); gtag('config', 'AW-974868566');</script><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Stellarium Web Online Star Map</title><meta name="description" content="Stellarium Web is a planetarium running in your web browser. It shows a realistic star map, just like what you see with the naked eye, binoculars or a telescope."><meta name="Keywords" content="Stellarium, Stellarium Web, planetarium, star map, sky map, astronomy, software, stars, planets, constellations, meteors, universe, astro, stars, planets, realistic, sky, program, scientific, educational, free, real, time, milky way, moon, mercury, venus, mars, earth, venus, jupiter, saturn, sun, real time, 3D, openGL, graphic, GL, chart, map, twinkle, photo-realistic"><link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900" rel="stylesheet"><link rel="icon" type="image/x-icon" href="https://d3ufh70wg9uzo4.cloudfront.net/favicon.ico"><meta name="theme-color" content="#000"><style type="text/css">#nightmode {
      background: #ff2200;
      pointer-events: none;
      height: 100vh;
      width: 100vw;
      position: absolute;
      z-index: 1000;
      mix-blend-mode: multiply;
      visibility: hidden;
    }</style><link href="https://d3ufh70wg9uzo4.cloudfront.net/js/chunk-2d2253ec.6784855b.js" rel="prefetch"><link href="https://d3ufh70wg9uzo4.cloudfront.net/css/app.3714d66a.css" rel="preload" as="style"><link href="https://d3ufh70wg9uzo4.cloudfront.net/css/chunk-vendors.bd381c0a.css" rel="preload" as="style"><link href="https://d3ufh70wg9uzo4.cloudfront.net/js/app.44b5ed00.js" rel="preload" as="script"><link href="https://d3ufh70wg9uzo4.cloudfront.net/js/chunk-vendors.a9e667ff.js" rel="preload" as="script"><link href="https://d3ufh70wg9uzo4.cloudfront.net/css/chunk-vendors.bd381c0a.css" rel="stylesheet"><link href="https://d3ufh70wg9uzo4.cloudfront.net/css/app.3714d66a.css" rel="stylesheet"></head><body><div id="nightmode"></div><noscript><strong>We're sorry but stellarium-web doesn't work properly without JavaScript enabled. Please enable it to continue.</strong></noscript><div id="app"><router-view></router-view></div><script src="https://d3ufh70wg9uzo4.cloudfront.net/js/chunk-vendors.a9e667ff.js"></script><script src="https://d3ufh70wg9uzo4.cloudfront.net/js/app.44b5ed00.js"></script></body></html>